included:
- DesafioTransbank

excluded:
- Pods

analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
- anyobject_protocol
- attributes
- closure_end_indentation
- closure_spacing
- contains_over_filter_count
- contains_over_filter_is_empty
- convenience_type
- discouraged_object_literal
- discouraged_optional_boolean
- empty_count
- empty_string
- explicit_init
- fatal_error_message
- file_length
- first_where
- force_unwrapping
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- modifier_order
- multiline_parameters
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- prohibited_super_call
- redundant_nil_coalescing
- sorted_first_last
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- yoda_condition
